package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/Jhosep2022/prueba-tecnica-go-graphql-productos/graph/generated"
	"github.com/Jhosep2022/prueba-tecnica-go-graphql-productos/graph/model"
)

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.CreateProductInput) (*model.Product, error) {
	product, err := r.productUseCase.CreateProduct(
		ctx,
		input.Name,
		input.Price,
		input.Stock,
	)
	if err != nil {
		return nil, err
	}
	return toProductModel(product), nil
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, id string, input model.UpdateProductInput) (*model.Product, error) {
	product, err := r.productUseCase.UpdateProduct(
		ctx,
		id,
		input.Name,
		input.Price,
	)
	if err != nil {
		return nil, err
	}
	return toProductModel(product), nil
}

// DeleteProduct is the resolver for the deleteProduct field.
func (r *mutationResolver) DeleteProduct(ctx context.Context, id string) (bool, error) {
	if err := r.productUseCase.DeleteProduct(ctx, id); err != nil {
		return false, err
	}

	return true, nil
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context) ([]*model.Product, error) {
	products, err := r.productUseCase.ListProducts(ctx)
	if err != nil {
		return nil, err
	}
	return toProductModels(products), nil
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id string) (*model.Product, error) {
	product, err := r.productUseCase.GetProductByID(ctx, id)
	if err != nil {
		return nil, err
	}
	return toProductModel(product), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
